const Map<String, String> arYE = {
  'app_name': 'كانبان كيت',
  'todo': 'جاهز للتنفيذ',
  'in_progress': 'قيد التنفيذ',
  'done': 'مكتمل',
  'add_task': 'إضافة مهمة',
  'task_title': 'عنوان المهمة',
  'task_description': 'وصف المهمة',
  'cancel': 'إلغاء',
  'add': 'إضافة',
  'no_tasks': 'لا يوجد مهام',
  'no_task_available': 'لا يوجد مهام متاحة',
  'edit_task': 'تعديل المهمة',
  'new_task': 'إضافة مهمة جديدة',
  'please_enter_title': 'الرجاء إدخال العنوان',
  'please_enter_description': 'الرجاء إدخال الوصف',
  'task_status': 'حالة المهمة',
  'priority': 'الأولوية',
  'due_date': 'تاريخ الانتهاء',
  'select_due_date': 'حدد تاريخ الانتهاء',
  'remove_due_date': 'إزالة تاريخ الانتهاء',
  'high': 'عالية',
  'medium': 'متوسطة',
  'low': 'منخفضة',
  'clear_due_date': 'مسح تاريخ الانتهاء',
  'update': 'تحديث',
  'create': 'إنشاء',
  'delete': 'حذف',
  'delete_task': 'حذف المهمة',
  'are_you_sure_delete': 'هل أنت متأكد أنك تريد الحذف',
  'language': 'لغة',
  'refresh': 'تحديث',
  'change_language': 'تغيير اللغة',
  'choose_language': 'اختر اللغة',
  'select_language': 'اختر اللغة',
  'theme': 'المظهر',
  'choose_theme': 'اختر المظهر',
  'light_theme': 'فاتح',
  'dark_theme': 'داكن',
  'system_theme': 'النظام',
  'always_use_light_theme': 'استخدم المظهر الفاتح دائماً',
  'always_use_dark_theme': 'استخدم المظهر الداكن دائماً',
  'follow_system_theme': 'اتبع مظهر النظام',
  'switch_theme': 'تبديل المظهر',

  // Onboarding
  'previous': 'السابق',
  'next': 'التالي',
  'skip': 'تخطي',
  'get_started': 'ابدأ الآن',
  'welcome_to_kanban_kit': 'مرحباً بك في كانبان كيت',
  'organize_tasks_effectively': 'نظم مهامك بفعالية',
  'kanban_kit_helps_you_manage_tasks':
      'كانبان كيت يساعدك في إدارة مهامك ومشاريعك باستخدام نهج لوحة كانبان البصرية البسيطة.',
  'create_and_manage_tasks': 'إنشاء وإدارة المهام',
  'stay_organized': 'ابق منظماً',
  'create_tasks_with_details':
      'أنشئ مهام مع الأوصاف والمواعيد النهائية والأولويات وتتبع تقدمها بسهولة.',
  'track_progress': 'تتبع التقدم',
  'visualize_workflow': 'تصور سير العمل',
  'move_tasks_between_columns':
      'انقل المهام بين أعمدة "جاهز للتنفيذ" و"قيد التنفيذ" و"مكتمل" لتصور سير عملك بوضوح.',
  'checklist_feature': 'ميزة قائمة التحقق',
  'break_down_complex_tasks': 'تقسيم المهام المعقدة',
  'add_checklist_items_to_tasks':
      'أضف عناصر قائمة التحقق إلى مهامك لتقسيم العمل المعقد إلى خطوات قابلة للإدارة.',
  'ready_to_begin_journey': 'مستعد لبدء رحلتك؟',
  'start_using_kanban_kit_today':
      'ابدأ باستخدام كانبان كيت اليوم لتعزيز إنتاجيتك والحفاظ على تنظيم مشاريعك!',
  'details_tab': 'تفاصيل',
  'checklist_tab': 'قائمة التحقق',
  'add_checklist_item': 'إضافة عنصر قائمة التحقق',
  'no_checklist_items': 'لا يوجد عناصر في قائمة التحقق',
  'add_items_above_to_create_checklist':
      'إضافة عناصر أعلاه لإنشاء قائمة التحقق',
  'adding_item': 'إضافة عنصر',
  'updating': 'تحديث',
  'choose_when_this_task_should_be_completed': 'اختر موعد إكمال المهمة',
  'task_checklist': 'قائمة التحقق من المهمة',
  'add_checklist_items_for_new_task': 'أضف عناصر تحقق لهذه المهمة الجديدة',
  'add_checklist_item_hint': 'إضافة عنصر تحقق...',
  'items_to_add': 'العناصر المراد إضافتها',
  'no_checklist_items_yet': 'لا توجد عناصر تحقق بعد',
  'add_items_above_to_break_down_task': 'أضف عناصر أعلاه لتقسيم المهمة',
  'new_items_to_add': 'عناصر جديدة للإضافة',
  'break_down_task_into_smaller_steps': 'قسّم هذه المهمة إلى خطوات أصغر',
  'view_all': 'عرض الكل',
  'items': 'عناصر',
  'checklist': 'قائمة التحقق',
  'created': 'تم الإنشاء',
  'of': 'من',
  'completed': 'مكتمل',
  'all_items_completed': 'تم إكمال جميع العناصر',
  'clear': 'مسح',
  'clear_completed_items': 'مسح العناصر المكتملة',
  'are_you_sure': 'هل أنت متأكد',
  'mark_all_items': 'تحديد جميع',
  'uncomplete_all_items': 'إلغاء تحديد الكل',
  'complete_all_items': 'تحديد جميع العناصر',
  'search_checklist_items': 'البحث في عناصر القائمة...',
  'edit_item': 'تحرير العنصر',
  'delete_item': 'حذف العنصر',
  'save_changes': 'حفظ التغييرات',
  'discard_changes': 'تجاهل التغييرات',
  'item_title_empty': 'عنوان العنصر لا يمكن أن يكون فارغاً',
  'tap_to_edit': 'اضغط للتحرير',
  'long_press_to_edit': 'اضغط مطولاً للتحرير',
  'mark_as_complete': 'تحديد كمكتمل',
  'mark_as_incomplete': 'تحديد كغير مكتمل',
  'add_item': 'إضافة عنصر',
  'add_items': 'إضافة عناصر',
  'add_multiple_items_hint': 'إضافة عناصر متعددة',
  'task_information': 'معلومات المهمة',
  'task_progress': 'تقدم المهمة',
  'all_tasks_completed': 'تم إكمال جميع المهام',
  'last_updated': 'آخر تحديث',
  'task_priority': 'أولوية المهمة',
  'task_due_date': 'تاريخ الانتهاء المحدد',
  'no_due_date': 'لا يوجد تاريخ نهائي',
  'no_description': 'لا يوجد وصف',
  "error": "خطأ",
  "success": "نجاح",
  "task_added_successfully": "تم إضافة المهمة بنجاح",
  "task_updated_successfully": "تم تحديث المهمة بنجاح",
  "task_deleted_successfully": "تم حذف المهمة بنجاح",
  "automatic_move": "تم النقل تلقائيًا",
  "task_moved_to": "تم نقل المهمة إلى {status}",
  "failed_to_load_tasks": "فشل في تحميل المهام",
  "failed_to_add_task": "فشل في إضافة المهمة",
  "failed_to_update_task": "فشل في تحديث المهمة",
  "failed_to_delete_task": "فشل في حذف المهمة",
  "tasks_moved_automatically": "تم نقل {count} مهمة تلقائيًا",
  "task_moved_to_status_automatically": "تم نقل المهمة إلى {status} تلقائيًا",
  'deleting': 'حذف',
  'task_moved_to_status': 'تم نقل المهمة إلى {status}',
  'single_line': 'سطر واحد',
  'multiple_lines': 'عدة أسطر',
  'add_multiple_items': 'إضافة عناصر متعددة',
  "error_loading_checklist": "فشل في تحميل قائمة المهام",
  "invalid_input": "إدخال غير صالح",
  "checklist_item_title_empty": "عنوان عنصر القائمة لا يمكن أن يكون فارغًا",
  "checklist_item_created_successfully": "تم إنشاء عنصر القائمة بنجاح",
  "checklist_items_created_successfully": "تم إنشاء {count} عناصر قائمة",
  "error_creating_item": "فشل في إنشاء عنصر القائمة",
  "error_creating_items": "فشل في إنشاء عناصر القائمة",
  "checklist_item_updated_successfully": "تم تحديث عنصر القائمة بنجاح",
  "error_updating_item": "فشل في تحديث عنصر القائمة",
  "error_toggling_item": "فشل في تبديل حالة عنصر القائمة",
  "error_deleting_item": "فشل في حذف عنصر القائمة",
  "checklist_item_deleted_successfully": "تم حذف عنصر القائمة بنجاح",
  "error_deleting_items": "فشل في حذف عناصر القائمة",
  "checklist_items_deleted_successfully": "تم حذف {count} عناصر قائمة",
  "error_reordering_items": "فشل في إعادة ترتيب عناصر القائمة",
  "error_moving_item": "فشل في نقل عنصر القائمة",
  "cleared_completed_items": "تم مسح جميع العناصر المكتملة",
  "error_clearing_items": "فشل في مسح العناصر المكتملة",
  "marked_all_items": "تم وضع جميع العناصر على {action}",
  "error_updating_all_items": "فشل في تحديث جميع العناصر",
  "error_searching_items": "فشل في البحث عن عناصر القائمة",
  "duplicated_checklist_items": "تم نسخ {count} عنصر قائمة",
  "error_duplicating_items": "فشل في نسخ عناصر القائمة",
  "task_moved_automatically": "تم نقل المهمة إلى {status} تلقائيًا",
  "loading": "جاري التحميل...",
  "organize_your_tasks_efficiently": "تنظيم مهامك بفعالية",

  // Board-related translations
  "create_new_board": "إنشاء لوحة جديدة",
  "edit_board": "تعديل اللوحة",
  "set_up_new_board": "قم بإعداد لوحتك الجديدة",
  "update_board_settings": "قم بتحديث إعدادات لوحتك",
  "board_name": "اسم اللوحة",
  "enter_board_name": "أدخل اسم اللوحة",
  "board_description": "الوصف",
  "describe_board_purpose": "اوصف الغرض من هذه اللوحة...",
  "board_color": "لون اللوحة",
  "description_optional": "الوصف (اختياري)",
  "please_enter_board_name": "يرجى إدخال اسم اللوحة",
  "board_name_too_long": "اسم اللوحة لا يمكن أن يتجاوز 255 حرف",
  "hex_color": "رمز اللون",
  "quick_colors": "الألوان السريعة",

  // Board actions
  "edit": "تعديل",
  "duplicate": "نسخ",
  "archive": "أرشفة",
  "archived": "مؤرشف",
  "just_now": "الآن",
  "days_ago": "منذ {count} أيام",
  "hours_ago": "منذ {count} ساعات",
  "minutes_ago": "منذ {count} دقائق",

  // Additional UI translations
  "search_boards": "البحث في اللوحات",
  "archived_boards": "اللوحات المؤرشفة",
  "your_boards": "لوحاتك",
  "search_results": "نتائج البحث",
  "no_boards_yet": "لا توجد لوحات بعد",
  "create_first_board": "أنشئ لوحتك الأولى للبدء في تنظيم مهامك",
  "add_board": "إضافة لوحة",
  "searching_for": "البحث عن",
  "archive_board": "أرشفة اللوحة",
  "delete_board": "حذف اللوحة",
  "duplicate_board": "نسخ اللوحة",
  "new_board_name": "اسم اللوحة الجديدة",
  "are_you_sure_archive": "هل أنت متأكد أنك تريد أرشفة",
  "cannot_be_undone": "لا يمكن التراجع عن هذا الإجراء",

  // Archived boards translations
  "no_archived_boards": "لا توجد لوحات مؤرشفة",
  "archived_boards_will_appear_here":
      "ستظهر اللوحات المؤرشفة هنا عندما تقوم بأرشفة لوحاتك",
  "go_back": "العودة",
  "restore_board": "استعادة اللوحة",
  "are_you_sure_restore": "هل أنت متأكد أنك تريد استعادة",
  "restore": "استعادة",
  "permanently_delete_board": "حذف اللوحة نهائياً",
  "permanently_delete_warning": "هل أنت متأكد أنك تريد حذف",
  "permanently_delete": "حذف نهائياً",
  "view_archived_boards": "عرض اللوحات المؤرشفة",
  "board_archived_successfully": "تم أرشفة اللوحة بنجاح",
  "board_restored_successfully": "تم استعادة اللوحة بنجاح",

  //List Transalation
  "your_lists": "قوائمك",
  "archived_lists": "قوائم مؤرشفة",
  "list_name": "اسم القائمة",

  // List-related translations
  "search_lists": "البحث في القوائم",
  "archive_all_lists": "أرشفة جميع القوائم",
  "restore_all_lists": "استعادة جميع القوائم",
  "board_settings": "إعدادات اللوحة",
  "add_list": "إضافة قائمة",
  "no_archived_lists": "لا توجد قوائم مؤرشفة",
  "archived_lists_will_appear_here_description":
      "ستظهر القوائم المؤرشفة هنا عندما تقوم بأرشفتها.",
  "no_lists_found": "لم يتم العثور على قوائم",
  "no_lists_match_search":
      "لا توجد قوائم تطابق معايير البحث الخاصة بك. حاول استخدام مصطلح بحث مختلف.",
  "clear_search": "مسح البحث",
  "no_lists_yet": "لا توجد قوائم بعد",
  "create_first_list_description":
      "أنشئ قائمتك الأولى لتنظيم المهام في هذه اللوحة.",
  "create_list": "إنشاء قائمة",
  "list_selected": "تم اختيار القائمة",
  "tapped_on_list": "تم النقر على القائمة: {title}",
  "archive_list": "أرشفة القائمة",
  "confirm_archive_list": "هل أنت متأكد أنك تريد أرشفة \"{title}\"؟",
  "delete_list": "حذف القائمة",
  "confirm_delete_list":
      "هل أنت متأكد أنك تريد حذف \"{title}\" نهائياً؟ لا يمكن التراجع عن هذا الإجراء.",
  "duplicate_list": "نسخ القائمة",
  "enter_name_for_duplicated_list": "أدخل اسماً للقائمة المنسوخة:",
  "move_to_board": "نقل إلى لوحة",
  "move_to_board_description": "سيتم تنفيذ وظيفة النقل إلى لوحة قريباً.",
  "archive_all_lists_dialog": "أرشفة جميع القوائم",
  "confirm_archive_all_lists":
      "هل أنت متأكد أنك تريد أرشفة جميع القوائم في هذه اللوحة؟",
  "restore_all_lists_dialog": "استعادة جميع القوائم",
  "confirm_restore_all_lists":
      "هل أنت متأكد أنك تريد استعادة جميع القوائم المؤرشفة؟",
  "board_settings_dialog": "إعدادات اللوحة",
  "board_settings_description": "سيتم تنفيذ وظيفة إعدادات اللوحة قريباً.",
  "enter_list_name": "أدخل اسم القائمة...",
  "archive_all": "أرشفة الكل",
  "restore_all": "استعادة الكل",
  "board_settings_title": "إعدادات اللوحة",

  // Card-related translations
  "status": "الحالة",
  "completed_at": "تم الإكمال في",
  "description": "الوصف",
  "add_card": "إضافة بطاقة",
  "edit_card": "تعديل البطاقة",
  "card_title": "عنوان البطاقة",
  "card_description": "وصف البطاقة",
  "save": "حفظ",
  "please_enter_card_title": "الرجاء إدخال عنوان للبطاقة",
  "card_added_successfully": "تمت إضافة البطاقة بنجاح",
  "card_updated_successfully": "تم تحديث البطاقة بنجاح",
  "card_deleted_successfully": "تم حذف البطاقة بنجاح",
  "failed_to_add_card": "فشل في إضافة البطاقة",
  "failed_to_update_card": "فشل في تحديث البطاقة",
  "failed_to_delete_card": "فشل في حذف البطاقة",
  "backlog": "متأخر",
  "inProgress": "قيد التنفيذ",
  "blocked": "محظور",
  "inReview": "قيد المراجعة",
  'update_list_settings': 'تحديث إعدادات القائمة',
  'setup_new_list': 'إعداد قائمة جديدة للوحة',
  'add_checklist': 'إضافة قائمة تحقق',
  'edit_checklist': 'تعديل قائمة التحقق',
  'checklist_name': 'اسم قائمة التحقق',
  'checklist_title': 'عنوان قائمة التحقق',
  'checklists': 'قوائم التحقق',
  'no_checklists': 'لا توجد قوائم تحقق بعد',
  'no_checklist_found': 'لم يتم العثور على أي قائمة تحقق',
  'no_checklist_match_search': 'لا توجد قائمة تحقق تطابق البحث',
  'enter_checklist_title': 'أدخل عنوان قائمة التحقق',
  'checklist_title_required': 'عنوان قائمة التحقق مطلوب',
  'checklist_title_too_long': 'عنوان قائمة التحقق طويل جدًا',
  'checklist_title_empty': 'عنوان قائمة التحقق لا يمكن أن يكون فارغًا',
  'archived_checklists': 'قوائم التحقق المؤرشفة',
  'no_archived_checklists': 'لا توجد قوائم تحقق مؤرشفة',
  'add_checklist_to_get_started': 'أضف قائمة تحقق للبدء',
  'view_archived': 'عرض المؤرشف',
  'progress': 'التقدم',
  'checklist_options': 'خيارات قائمة التحقق',
  'rename': 'إعادة تسمية',
  'edit_checklist_title': 'تعديل عنوان قائمة التحقق',
  'create_copy_of_checklist': 'إنشاء نسخة من قائمة التحقق',
  'hide_checklist_from_view': 'إخفاء قائمة التحقق من العرض',
  'restore_checklist_to_view': 'استعادة قائمة التحقق للعرض',
  'move_to_card': 'نقل إلى البطاقة',
  'move_checklist_to_another_card': 'نقل قائمة التحقق إلى بطاقة أخرى',
  'delete_checklist_permanently': 'حذف قائمة التحقق نهائيًا',
  'delete_checklist': 'حذف قائمة التحقق',
  'delete_checklist_confirmation':
      'هل أنت متأكد من حذف قائمة التحقق هذه؟ لا يمكن التراجع عن هذا الإجراء.',
  'duplicate_checklist': 'تكرار قائمة التحقق',
  'copy': 'نسخ',
  'unarchive': 'إلغاء الأرشفة',
  'options': 'خيارات',
  'update_list': 'تحديث القائمة',
  'no_cards': 'لا توجد بطاقات',
  'no_cards_found': 'لم يتم العثور على أي بطاقات',

  // Checklist Item Translations
  'checklist_item_created': 'تم إنشاء عنصر القائمة المرجعية بنجاح',
  'checklist_items_created': 'عنصر من عناصر القائمة المرجعية تم إنشاؤها بنجاح',
  'checklist_item_updated': 'تم تحديث عنصر القائمة المرجعية بنجاح',
  'checklist_item_deleted': 'تم حذف عنصر القائمة المرجعية بنجاح',
  'checklist_item_archived': 'تم أرشفة عنصر القائمة المرجعية بنجاح',
  'checklist_item_unarchived': 'تم إلغاء أرشفة عنصر القائمة المرجعية بنجاح',
  'completed_items_cleared': 'تم مسح العناصر المكتملة بنجاح',
  'all_items_marked_completed': 'تم وضع علامة على جميع العناصر كمكتملة',
  'all_items_marked_pending': 'تم وضع علامة على جميع العناصر كمعلقة',
  'edit_checklist_item': 'تعديل عنصر القائمة المرجعية',
  'edit_checklist_item_description': 'تحديث عنوان عنصر القائمة المرجعية هذا',
  'add_first_checklist_item': 'أضف عنصر القائمة المرجعية الأول للبدء',
  'rename_checklist_description': 'تغيير اسم هذه القائمة المرجعية',
  'archive_checklist_description': 'إخفاء هذه القائمة المرجعية من العرض النشط',
  'unarchive_checklist_description':
      'استعادة هذه القائمة المرجعية إلى العرض النشط',
  'duplicate_checklist_description':
      'إنشاء نسخة من هذه القائمة المرجعية مع جميع العناصر',
  'delete_checklist_description':
      'حذف هذه القائمة المرجعية وجميع العناصر نهائياً',
  'no_checklists_description':
      'إنشاء قوائم مرجعية لتنظيم مهامك مع عناصر قابلة للتحديد',
  'create_first_checklist': 'إنشاء قائمة تحقق',
  'rename_checklist': 'تغيير اسم القائمة',

  // Image Picker Translations
  'select_image_source': 'اختر مصدر الصورة',
  'select_from_gallery': 'اختر من المعرض',
  'take_photo': 'التقط صورة',
  'remove_image': 'إزالة الصورة',
  'current_image': 'الصورة الحالية',
  'choose_from_existing_photos': 'اختر من صورك الموجودة',
  'capture_new_photo': 'التقط صورة جديدة بالكاميرا',
  'remove_current_image': 'إزالة الصورة الحالية',
  'close_without_changes': 'إغلاق بدون تغييرات',
  'confirm_remove_image': 'هل أنت متأكد من إزالة هذه الصورة؟',
  'image_selected_successfully': 'تم اختيار الصورة بنجاح',
  'image_removed_successfully': 'تم حذف الصورة بنجاح',
  'no_image_selected': 'لم يتم اختيار أي صورة',
  'error_picking_image': 'حدث خطأ أثناء اختيار الصورة',
  'error_removing_image': 'حدث خطأ أثناء إزالة الصورة',
  'remove': 'إزالة',

  // Card Cover Translations
  'card_cover': 'غلاف البطاقة',
  'add_cover': 'إضافة غلاف',
  'change_cover': 'تغيير الغلاف',
  'remove_cover': 'إزالة الغلاف',
  'cover_color': 'لون الغلاف',
  'cover_image': 'صورة الغلاف',
  'select_cover_type': 'اختر نوع الغلاف',
  'choose_cover_color': 'اختر لوناً لغلاف البطاقة',
  'choose_cover_image': 'اختر صورة لغلاف البطاقة',
  'no_cover': 'بدون غلاف',
  'cover_updated_successfully': 'تم تحديث الغلاف بنجاح',
  'cover_removed_successfully': 'تم حذف الغلاف بنجاح',
  'set_due_date': 'تعيين تاريخ الانتهاء',
  
  // Due Date Status Translations
  'due_date_complete': 'مكتمل',
  'due_date_overdue': 'متأخر',
  'due_date_due_today': 'مطلوب اليوم',
  'due_date_due_soon': 'مطلوب قريباً',

  // ترجمات التسميات
  'labels': 'التسميات',
  'label': 'تسمية',
  'label_name': 'اسم التسمية',
  'label_color': 'لون التسمية',
  'add_label': 'إضافة تسمية',
  'edit_label': 'تعديل التسمية',
  'delete_label': 'حذف التسمية',
  'duplicate_label': 'نسخ التسمية',
  'search_labels': 'البحث في التسميات',
  'no_labels': 'لا توجد تسميات',
  'no_labels_found': 'لم يتم العثور على تسميات',
  'label_name_required': 'اسم التسمية مطلوب',
  'label_color_required': 'لون التسمية مطلوب',
  'label_name_already_exists': 'اسم التسمية موجود بالفعل',
  'invalid_label_data': 'بيانات التسمية غير صحيحة',
  'label_created_successfully': 'تم إنشاء التسمية بنجاح',
  'label_updated_successfully': 'تم تحديث التسمية بنجاح',
  'label_deleted_successfully': 'تم حذف التسمية بنجاح',
  'label_restored_successfully': 'تم استعادة التسمية بنجاح',
  'label_permanently_deleted_successfully': 'تم حذف التسمية نهائياً بنجاح',
  'labels_created_successfully': 'تم إنشاء التسميات بنجاح',
  'labels_deleted_successfully': 'تم حذف التسميات بنجاح',
  'error_creating_label': 'خطأ في إنشاء التسمية',
  'error_loading_label': 'خطأ في تحميل التسمية',
  'error_loading_labels': 'خطأ في تحميل التسميات',
  'error_loading_deleted_labels': 'خطأ في تحميل التسميات المحذوفة',
  'error_updating_label': 'خطأ في تحديث التسمية',
  'error_deleting_label': 'خطأ في حذف التسمية',
  'error_restoring_label': 'خطأ في استعادة التسمية',
  'error_permanently_deleting_label': 'خطأ في الحذف النهائي للتسمية',
  'error_searching_labels': 'خطأ في البحث في التسميات',
  'error_loading_labels_by_color': 'خطأ في تحميل التسميات حسب اللون',
  'error_loading_label_stats': 'خطأ في تحميل إحصائيات التسميات',
  'error_duplicating_label': 'خطأ في نسخ التسمية',
  'error_creating_labels': 'خطأ في إنشاء التسميات',
  'error_deleting_labels': 'خطأ في حذف التسميات',
  'error_cleaning_up_labels': 'خطأ في تنظيف التسميات',
  'label_not_found': 'التسمية غير موجودة',
  'labels_removed': 'تسمية محذوفة',
  'cleanup_completed': 'تم التنظيف بنجاح',

  // ترجمات تسميات البطاقات
  'card_labels': 'تسميات البطاقة',
  'assign_label': 'تعيين تسمية',
  'remove_label': 'إزالة التسمية',
  'label_already_assigned_to_card': 'التسمية معينة للبطاقة بالفعل',
  'label_not_assigned_to_card': 'التسمية غير معينة للبطاقة',
  'label_assigned_to_card_successfully': 'تم تعيين التسمية للبطاقة بنجاح',
  'label_removed_from_card_successfully': 'تم إزالة التسمية من البطاقة بنجاح',
  'all_labels_removed_from_card_successfully': 'تم إزالة جميع التسميات من البطاقة بنجاح',
  'label_assignment_restored_successfully': 'تم استعادة تعيين التسمية بنجاح',
  'label_assignment_permanently_deleted_successfully': 'تم حذف تعيين التسمية نهائياً بنجاح',
  'labels_assigned_to_card_successfully': 'تم تعيين التسميات للبطاقة بنجاح',
  'labels_removed_from_card_successfully': 'تم إزالة التسميات من البطاقة بنجاح',
  'card_labels_updated_successfully': 'تم تحديث تسميات البطاقة بنجاح',
  'error_assigning_label_to_card': 'خطأ في تعيين التسمية للبطاقة',
  'error_removing_label_from_card': 'خطأ في إزالة التسمية من البطاقة',
  'error_loading_card_labels': 'خطأ في تحميل تسميات البطاقة',
  'error_loading_cards_by_label': 'خطأ في تحميل البطاقات حسب التسمية',
  'error_loading_card_label': 'خطأ في تحميل تسمية البطاقة',
  'error_removing_all_labels_from_card': 'خطأ في إزالة جميع التسميات من البطاقة',
  'error_restoring_label_assignment': 'خطأ في استعادة تعيين التسمية',
  'error_permanently_deleting_label_assignment': 'خطأ في الحذف النهائي لتعيين التسمية',
  'error_loading_label_usage_stats': 'خطأ في تحميل إحصائيات استخدام التسمية',
  'error_assigning_labels_to_card': 'خطأ في تعيين التسميات للبطاقة',
  'error_removing_labels_from_card': 'خطأ في إزالة التسميات من البطاقة',
  'error_updating_card_labels': 'خطأ في تحديث تسميات البطاقة',
  'error_toggling_label_assignment': 'خطأ في تبديل تعيين التسمية',
  'error_loading_all_card_labels': 'خطأ في تحميل جميع تسميات البطاقات',
  'error_cleaning_up_label_assignments': 'خطأ في تنظيف تعيينات التسميات',
  'no_labels_to_copy': 'لا توجد تسميات للنسخ',
  'no_labels_to_move': 'لا توجد تسميات للنقل',
  'error_copying_labels_to_card': 'خطأ في نسخ التسميات للبطاقة',
  'error_moving_labels_to_card': 'خطأ في نقل التسميات للبطاقة',
  'label_assignments_removed': 'تعيين تسمية محذوف',

  // Trash Keys
  'trash': 'سلة المحذوفات',
  'trash_bin': 'سلة المحذوفات',
  'restore_item': 'استعادة',
  'permanent_delete': 'حذف نهائي',
  'empty_trash': 'إفراغ السلة',
  'clean_old_items': 'تنظيف العناصر القديمة',
  'trash_is_empty': 'سلة المحذوفات فارغة',
  'no_deleted_items': 'لا توجد عناصر محذوفة',
  'search_in_trash': 'البحث في سلة المحذوفات...',
  'no_search_results': 'لا توجد نتائج',
  'clear_trash_search': 'مسح البحث',
  'show_all': 'عرض الكل',
  'total_deleted_items': 'إجمالي العناصر المحذوفة',
  'item_restored': 'تم استعادة العنصر بنجاح',
  'item_permanently_deleted': 'تم حذف العنصر نهائياً',
  'confirm_permanent_delete': 'هل أنت متأكد من حذف هذا العنصر نهائياً؟',
  'confirm_empty_trash': 'هل أنت متأكد من إفراغ سلة المحذوفات؟',
  'confirm_clean_old_items': 'تنظيف العناصر الأقدم من الأيام المحددة؟',
  'items_emptied_from_trash': 'عنصر تم حذفه نهائياً من سلة المحذوفات',
  'old_items_cleaned': 'عنصر قديم تم تنظيفه من سلة المحذوفات',
  'no_old_items_to_clean': 'لا توجد عناصر قديمة للتنظيف',
  'deleted_ago': 'محذوف',
  'belongs_to': 'ينتمي إلى',
  'item_type': 'النوع',
  'created_at': 'تاريخ الإنشاء',
  'updated_at': 'تاريخ التحديث',
  'deleted_at': 'تاريخ الحذف',
  'item_details': 'تفاصيل العنصر',
  'trash_board': 'لوحة',
  'trash_list': 'قائمة',
  'trash_card': 'بطاقة',
  'trash_checklist': 'قائمة تحقق',
  'trash_checklist_item': 'عنصر تحقق',
  'trash_label': 'تسمية',
  'trash_boards': 'اللوحات',
  'trash_lists': 'القوائم',
  'trash_cards': 'البطاقات',
  'trash_checklists': 'قوائم التحقق',
  'trash_checklist_items': 'عناصر التحقق',
  'trash_labels': 'التسميات',
  'trash_all': 'الكل',
  'trash_days': 'أيام',
  'trash_hours': 'ساعات',
  'trash_minutes': 'دقائق',
  'trash_now': 'الآن',
  'trash_ago': 'منذ',
  'trash_since': 'منذ',
  
  // Comments
  'comments': 'التعليقات',
  'comment': 'تعليق',
  'add_comment': 'إضافة تعليق',
  'edit_comment': 'تعديل التعليق',
  'delete_comment': 'حذف التعليق',
  'comment_added': 'تم إضافة التعليق بنجاح',
  'comment_updated': 'تم تحديث التعليق بنجاح',
  'comment_deleted': 'تم حذف التعليق بنجاح',
  'comment_restored': 'تم استعادة التعليق بنجاح',
  'no_comments': 'لا توجد تعليقات بعد',
  'write_comment': 'اكتب تعليقاً...',
  'comment_placeholder': 'أضف تعليقك هنا',
  'edited_comment': 'معدّل',
  'deleted_comment': 'محذوف',
  'comment_count': 'تعليق',
  
  // Attachments
  'attachments': 'المرفقات',
  'attachment': 'مرفق',
  'add_attachment': 'إضافة مرفق',
  'delete_attachment': 'حذف المرفق',
  'attachment_added': 'تم إضافة المرفق بنجاح',
  'attachment_deleted': 'تم حذف المرفق بنجاح',
  'attachment_restored': 'تم استعادة المرفق بنجاح',
  'no_attachments': 'لا توجد مرفقات بعد',
  'select_file': 'اختر ملف',
  'select_image': 'اختر صورة',
  'select_document': 'اختر مستند',
  'attachment_count': 'مرفق',
  'total_size': 'الحجم الإجمالي',
  'file_size': 'حجم الملف',
  'file_name': 'اسم الملف',
  'file_type': 'نوع الملف',
  'upload_file': 'رفع ملف',
  'download_file': 'تحميل',
  'view_file': 'عرض',
  'images': 'الصور',
  'documents': 'المستندات',
  'videos': 'الفيديوهات',
  'audio': 'الصوتيات',
  'other': 'أخرى',
  
  // Activity Log
  'activity_log': 'سجل النشاطات',
  'activity': 'النشاط',
  'recent_activity': 'النشاطات الأخيرة',
  'today_activity': 'نشاطات اليوم',
  'no_activity': 'لا توجد نشاطات بعد',
  'activity_timeline': 'الجدول الزمني للنشاطات',
  'view_activity': 'عرض النشاطات',
  'clear_activity': 'مسح النشاطات',
  'delete_old_activity': 'حذف النشاطات القديمة',
  'activity_cleared': 'تم مسح النشاطات بنجاح',
  'old_activity_deleted': 'تم حذف النشاطات القديمة بنجاح',
  
  // Activity Actions
  'action_created': 'تم الإنشاء',
  'action_updated': 'تم التحديث',
  'action_deleted': 'تم الحذف',
  'action_moved': 'تم النقل',
  'action_archived': 'تم الأرشفة',
  'action_restored': 'تم الاستعادة',
  'action_completed': 'تم الإكمال',
  'action_uncompleted': 'تم إلغاء الإكمال',
  
  // Entity Types
  'entity_board': 'لوحة',
  'entity_list': 'قائمة',
  'entity_card': 'بطاقة',
  'entity_checklist': 'قائمة تحقق',
  'entity_comment': 'تعليق',
  'entity_attachment': 'مرفق',
  'entity_label': 'تسمية',
  
  // Common Actions
  'post': 'نشر',
  'send': 'إرسال',
  'reply': 'رد',
  'edited': 'معدّل',
  'today': 'اليوم',
  'yesterday': 'أمس',
  'this_week': 'هذا الأسبوع',
  'this_month': 'هذا الشهر',
  'older': 'أقدم',
  
  // Confirmation Messages
  'confirm_delete_comment': 'هل أنت متأكد من حذف هذا التعليق؟',
  'confirm_delete_attachment': 'هل أنت متأكد من حذف هذا المرفق؟',
  'confirm_clear_activity': 'هل أنت متأكد من مسح جميع سجلات النشاطات؟',
  'confirm_delete_old_activity': 'هل أنت متأكد من حذف سجلات النشاطات القديمة؟',
  
  // Error Messages
  'error_loading_comments': 'خطأ في تحميل التعليقات',
  'error_adding_comment': 'خطأ في إضافة التعليق',
  'error_updating_comment': 'خطأ في تحديث التعليق',
  'error_deleting_comment': 'خطأ في حذف التعليق',
  'error_loading_attachments': 'خطأ في تحميل المرفقات',
  'error_adding_attachment': 'خطأ في إضافة المرفق',
  'error_deleting_attachment': 'خطأ في حذف المرفق',
  'error_loading_activity': 'خطأ في تحميل النشاطات',
  'comment_cannot_be_empty': 'لا يمكن أن يكون التعليق فارغاً',
  'file_not_selected': 'لم يتم اختيار ملف',
};
