const Map<String, String> arYE = {
  'app_name': 'كانبان كيت',
  'todo': 'جاهز للتنفيذ',
  'in_progress': 'قيد التنفيذ',
  'done': 'مكتمل',
  'add_task': 'إضافة مهمة',
  'task_title': 'عنوان المهمة',
  'task_description': 'وصف المهمة',
  'cancel': 'إلغاء',
  'add': 'إضافة',
  'no_tasks': 'لا يوجد مهام',
  'no_task_available': 'لا يوجد مهام متاحة',
  'edit_task': 'تعديل المهمة',
  'new_task': 'إضافة مهمة جديدة',
  'please_enter_title': 'الرجاء إدخال العنوان',
  'please_enter_description': 'الرجاء إدخال الوصف',
  'task_status': 'حالة المهمة',
  'priority': 'الأولوية',
  'due_date': 'تاريخ الانتهاء',
  'select_due_date': 'حدد تاريخ الانتهاء',
  'high': 'عالية',
  'medium': 'متوسطة',
  'low': 'منخفضة',
  'clear_due_date': 'مسح تاريخ الانتهاء',
  'update': 'تحديث',
  'create': 'إنشاء',
  'delete': 'حذف',
  'delete_task': 'حذف المهمة',
  'are_you_sure_delete': 'هل أنت متأكد أنك تريد الحذف',
  'language': 'لغة',
  'refresh': 'تحديث',
  'change_language': 'تغيير اللغة',
  'choose_language': 'اختر اللغة',
  'select_language': 'اختر اللغة',
  'theme': 'المظهر',
  'choose_theme': 'اختر المظهر',
  'light_theme': 'فاتح',
  'dark_theme': 'داكن',
  'system_theme': 'النظام',
  'always_use_light_theme': 'استخدم المظهر الفاتح دائماً',
  'always_use_dark_theme': 'استخدم المظهر الداكن دائماً',
  'follow_system_theme': 'اتبع مظهر النظام',
  'switch_theme': 'تبديل المظهر',

  // Onboarding
  'previous': 'السابق',
  'next': 'التالي',
  'skip': 'تخطي',
  'get_started': 'ابدأ الآن',
  'welcome_to_kanban_kit': 'مرحباً بك في كانبان كيت',
  'organize_tasks_effectively': 'نظم مهامك بفعالية',
  'kanban_kit_helps_you_manage_tasks':
      'كانبان كيت يساعدك في إدارة مهامك ومشاريعك باستخدام نهج لوحة كانبان البصرية البسيطة.',
  'create_and_manage_tasks': 'إنشاء وإدارة المهام',
  'stay_organized': 'ابق منظماً',
  'create_tasks_with_details':
      'أنشئ مهام مع الأوصاف والمواعيد النهائية والأولويات وتتبع تقدمها بسهولة.',
  'track_progress': 'تتبع التقدم',
  'visualize_workflow': 'تصور سير العمل',
  'move_tasks_between_columns':
      'انقل المهام بين أعمدة "جاهز للتنفيذ" و"قيد التنفيذ" و"مكتمل" لتصور سير عملك بوضوح.',
  'checklist_feature': 'ميزة قائمة التحقق',
  'break_down_complex_tasks': 'تقسيم المهام المعقدة',
  'add_checklist_items_to_tasks':
      'أضف عناصر قائمة التحقق إلى مهامك لتقسيم العمل المعقد إلى خطوات قابلة للإدارة.',
  'ready_to_begin_journey': 'مستعد لبدء رحلتك؟',
  'start_using_kanban_kit_today':
      'ابدأ باستخدام كانبان كيت اليوم لتعزيز إنتاجيتك والحفاظ على تنظيم مشاريعك!',
  'details_tab': 'تفاصيل',
  'checklist_tab': 'قائمة التحقق',
  'add_checklist_item': 'إضافة عنصر قائمة التحقق',
  'no_checklist_items': 'لا يوجد عناصر في قائمة التحقق',
  'add_items_above_to_create_checklist':
      'إضافة عناصر أعلاه لإنشاء قائمة التحقق',
  'adding_item': 'إضافة عنصر',
  'updating': 'تحديث',
  'choose_when_this_task_should_be_completed': 'اختر موعد إكمال المهمة',
  'task_checklist': 'قائمة التحقق من المهمة',
  'add_checklist_items_for_new_task': 'أضف عناصر تحقق لهذه المهمة الجديدة',
  'add_checklist_item_hint': 'إضافة عنصر تحقق...',
  'items_to_add': 'العناصر المراد إضافتها',
  'no_checklist_items_yet': 'لا توجد عناصر تحقق بعد',
  'add_items_above_to_break_down_task': 'أضف عناصر أعلاه لتقسيم المهمة',
  'new_items_to_add': 'عناصر جديدة للإضافة',
  'break_down_task_into_smaller_steps': 'قسّم هذه المهمة إلى خطوات أصغر',
  'view_all': 'عرض الكل',
  'items': 'عناصر',
  'checklist': 'قائمة التحقق',
  'created': 'تم الإنشاء',
  'of': 'من',
  'completed': 'مكتمل',
  'all_items_completed': 'تم إكمال جميع العناصر',
  'clear': 'مسح',
  'clear_completed_items': 'مسح العناصر المكتملة',
  'are_you_sure': 'هل أنت متأكد',
  'mark_all_items': 'تحديد جميع',
  'uncomplete_all_items': 'إلغاء تحديد الكل',
  'complete_all_items': 'تحديد جميع العناصر',
  'search_checklist_items': 'البحث في عناصر القائمة...',
  'edit_item': 'تحرير العنصر',
  'delete_item': 'حذف العنصر',
  'save_changes': 'حفظ التغييرات',
  'discard_changes': 'تجاهل التغييرات',
  'item_title_empty': 'عنوان العنصر لا يمكن أن يكون فارغاً',
  'tap_to_edit': 'اضغط للتحرير',
  'long_press_to_edit': 'اضغط مطولاً للتحرير',
  'mark_as_complete': 'تحديد كمكتمل',
  'mark_as_incomplete': 'تحديد كغير مكتمل',
  'add_item': 'إضافة عنصر',
  'add_items': 'إضافة عناصر',
  'add_multiple_items_hint': 'إضافة عناصر متعددة',
  'task_information': 'معلومات المهمة',
  'task_progress': 'تقدم المهمة',
  'all_tasks_completed': 'تم إكمال جميع المهام',
  'last_updated': 'آخر تحديث',
  'task_priority': 'أولوية المهمة',
  'task_due_date': 'تاريخ الانتهاء المحدد',
  'no_due_date': 'لا يوجد تاريخ نهائي',
  'no_description': 'لا يوجد وصف',
  "error": "خطأ",
  "success": "نجاح",
  "task_added_successfully": "تم إضافة المهمة بنجاح",
  "task_updated_successfully": "تم تحديث المهمة بنجاح",
  "task_deleted_successfully": "تم حذف المهمة بنجاح",
  "automatic_move": "تم النقل تلقائيًا",
  "task_moved_to": "تم نقل المهمة إلى {status}",
  "failed_to_load_tasks": "فشل في تحميل المهام",
  "failed_to_add_task": "فشل في إضافة المهمة",
  "failed_to_update_task": "فشل في تحديث المهمة",
  "failed_to_delete_task": "فشل في حذف المهمة",
  "tasks_moved_automatically": "تم نقل {count} مهمة تلقائيًا",
  "task_moved_to_status_automatically": "تم نقل المهمة إلى {status} تلقائيًا",
  'deleting': 'حذف',
  'task_moved_to_status': 'تم نقل المهمة إلى {status}',
  'single_line': 'سطر واحد',
  'multiple_lines': 'عدة أسطر',
  'add_multiple_items': 'إضافة عناصر متعددة',
  "error_loading_checklist": "فشل في تحميل قائمة المهام",
  "invalid_input": "إدخال غير صالح",
  "checklist_item_title_empty": "عنوان عنصر القائمة لا يمكن أن يكون فارغًا",
  "checklist_item_created_successfully": "تم إنشاء عنصر القائمة بنجاح",
  "checklist_items_created_successfully": "تم إنشاء {count} عناصر قائمة",
  "error_creating_item": "فشل في إنشاء عنصر القائمة",
  "error_creating_items": "فشل في إنشاء عناصر القائمة",
  "checklist_item_updated_successfully": "تم تحديث عنصر القائمة بنجاح",
  "error_updating_item": "فشل في تحديث عنصر القائمة",
  "error_toggling_item": "فشل في تبديل حالة عنصر القائمة",
  "error_deleting_item": "فشل في حذف عنصر القائمة",
  "checklist_item_deleted_successfully": "تم حذف عنصر القائمة بنجاح",
  "error_deleting_items": "فشل في حذف عناصر القائمة",
  "checklist_items_deleted_successfully": "تم حذف {count} عناصر قائمة",
  "error_reordering_items": "فشل في إعادة ترتيب عناصر القائمة",
  "error_moving_item": "فشل في نقل عنصر القائمة",
  "cleared_completed_items": "تم مسح جميع العناصر المكتملة",
  "error_clearing_items": "فشل في مسح العناصر المكتملة",
  "marked_all_items": "تم وضع جميع العناصر على {action}",
  "error_updating_all_items": "فشل في تحديث جميع العناصر",
  "error_searching_items": "فشل في البحث عن عناصر القائمة",
  "duplicated_checklist_items": "تم نسخ {count} عنصر قائمة",
  "error_duplicating_items": "فشل في نسخ عناصر القائمة",
  "task_moved_automatically": "تم نقل المهمة إلى {status} تلقائيًا",
  "loading": "جاري التحميل...",
  "organize_your_tasks_efficiently": "تنظيم مهامك بفعالية",

  // Board-related translations
  "create_new_board": "إنشاء لوحة جديدة",
  "edit_board": "تعديل اللوحة",
  "set_up_new_board": "قم بإعداد لوحتك الجديدة",
  "update_board_settings": "قم بتحديث إعدادات لوحتك",
  "board_name": "اسم اللوحة",
  "enter_board_name": "أدخل اسم اللوحة",
  "board_description": "الوصف",
  "describe_board_purpose": "اوصف الغرض من هذه اللوحة...",
  "board_color": "لون اللوحة",
  "description_optional": "الوصف (اختياري)",
  "please_enter_board_name": "يرجى إدخال اسم اللوحة",
  "board_name_too_long": "اسم اللوحة لا يمكن أن يتجاوز 255 حرف",
  "hex_color": "رمز اللون",
  "quick_colors": "الألوان السريعة",

  // Board actions
  "edit": "تعديل",
  "duplicate": "نسخ",
  "archive": "أرشفة",
  "archived": "مؤرشف",
  "just_now": "الآن",
  "days_ago": "منذ {count} أيام",
  "hours_ago": "منذ {count} ساعات",
  "minutes_ago": "منذ {count} دقائق",

  // Additional UI translations
  "search_boards": "البحث في اللوحات",
  "archived_boards": "اللوحات المؤرشفة",
  "your_boards": "لوحاتك",
  "search_results": "نتائج البحث",
  "no_boards_yet": "لا توجد لوحات بعد",
  "create_first_board": "أنشئ لوحتك الأولى للبدء في تنظيم مهامك",
  "add_board": "إضافة لوحة",
  "searching_for": "البحث عن",
  "archive_board": "أرشفة اللوحة",
  "delete_board": "حذف اللوحة",
  "duplicate_board": "نسخ اللوحة",
  "new_board_name": "اسم اللوحة الجديدة",
  "are_you_sure_archive": "هل أنت متأكد أنك تريد أرشفة",
  "cannot_be_undone": "لا يمكن التراجع عن هذا الإجراء",

  // Archived boards translations
  "no_archived_boards": "لا توجد لوحات مؤرشفة",
  "archived_boards_will_appear_here":
      "ستظهر اللوحات المؤرشفة هنا عندما تقوم بأرشفة لوحاتك",
  "go_back": "العودة",
  "restore_board": "استعادة اللوحة",
  "are_you_sure_restore": "هل أنت متأكد أنك تريد استعادة",
  "restore": "استعادة",
  "permanently_delete_board": "حذف اللوحة نهائياً",
  "permanently_delete_warning": "هل أنت متأكد أنك تريد حذف",
  "permanently_delete": "حذف نهائياً",
  "view_archived_boards": "عرض اللوحات المؤرشفة",
  "board_archived_successfully": "تم أرشفة اللوحة بنجاح",
  "board_restored_successfully": "تم استعادة اللوحة بنجاح",
};
