const Map<String, String> arYE = {
  'app_name': 'كانبان كيت',
  'todo': 'جاهز للتنفيذ',
  'in_progress': 'قيد التنفيذ',
  'done': 'مكتمل',
  'add_task': 'إضافة مهمة',
  'task_title': 'عنوان المهمة',
  'task_description': 'وصف المهمة',
  'cancel': 'إلغاء',
  'add': 'إضافة',
  'no_tasks': 'لا يوجد مهام',
  'no_task_available': 'لا يوجد مهام متاحة',
  'edit_task': 'تعديل المهمة',
  'new_task': 'إضافة مهمة جديدة',
  'please_enter_title': 'الرجاء إدخال العنوان',
  'please_enter_description': 'الرجاء إدخال الوصف',
  'task_status': 'حالة المهمة',
  'priority': 'الأولوية',
  'due_date': 'تاريخ الانتهاء',
  'select_due_date': 'حدد تاريخ الانتهاء',
  'high': 'عالية',
  'medium': 'متوسطة',
  'low': 'منخفضة',
  'clear_due_date': 'مسح تاريخ الانتهاء',
  'update': 'تحديث',
  'create': 'إنشاء',
  'delete': 'حذف',
  'delete_task': 'حذف المهمة',
  'are_you_sure_delete': 'هل أنت متأكد أنك تريد الحذف',
  'language': 'لغة',
  'refresh': 'تحديث',
  'change_language': 'تغيير اللغة',
  'choose_language': 'اختر اللغة',
  'select_language': 'اختر اللغة',
  'theme': 'المظهر',
  'choose_theme': 'اختر المظهر',
  'light_theme': 'فاتح',
  'dark_theme': 'داكن',
  'system_theme': 'النظام',
  'always_use_light_theme': 'استخدم المظهر الفاتح دائماً',
  'always_use_dark_theme': 'استخدم المظهر الداكن دائماً',
  'follow_system_theme': 'اتبع مظهر النظام',
  'switch_theme': 'تبديل المظهر',
  'details_tab': 'تفاصيل',
  'checklist_tab': 'قائمة التحقق',
  'add_checklist_item': 'إضافة عنصر قائمة التحقق',
  'no_checklist_items': 'لا يوجد عناصر في قائمة التحقق',
  'add_items_above_to_create_checklist':
      'إضافة عناصر أعلاه لإنشاء قائمة التحقق',
  'adding_item': 'إضافة عنصر',
  'updating': 'تحديث',
  'choose_when_this_task_should_be_completed': 'اختر موعد إكمال المهمة',
  'task_checklist': 'قائمة التحقق من المهمة',
  'add_checklist_items_for_new_task': 'أضف عناصر تحقق لهذه المهمة الجديدة',
  'add_checklist_item_hint': 'إضافة عنصر تحقق...',
  'items_to_add': 'العناصر المراد إضافتها',
  'no_checklist_items_yet': 'لا توجد عناصر تحقق بعد',
  'add_items_above_to_break_down_task': 'أضف عناصر أعلاه لتقسيم المهمة',
  'new_items_to_add': 'عناصر جديدة للإضافة',
  'break_down_task_into_smaller_steps': 'قسّم هذه المهمة إلى خطوات أصغر',
  'view_all': 'عرض الكل',
  'items': 'عناصر',
  'checklist': 'قائمة التحقق',
  'created': 'تم الإنشاء',
  'of': 'من',
  'completed': 'مكتمل',
  'all_items_completed': 'تم إكمال جميع العناصر',
  'clear': 'مسح',
  'clear_completed_items': 'مسح العناصر المكتملة',
  'are_you_sure': 'هل أنت متأكد',
  'mark_all_items': 'تحديد جميع',
  'uncomplete_all_items': 'إلغاء تحديد الكل',
  'complete_all_items': 'تحديد جميع العناصر',
  'search_checklist_items': 'البحث في عناصر القائمة...',
  'edit_item': 'تحرير العنصر',
  'delete_item': 'حذف العنصر',
  'save_changes': 'حفظ التغييرات',
  'discard_changes': 'تجاهل التغييرات',
  'item_title_empty': 'عنوان العنصر لا يمكن أن يكون فارغاً',
  'tap_to_edit': 'اضغط للتحرير',
  'long_press_to_edit': 'اضغط مطولاً للتحرير',
  'mark_as_complete': 'تحديد كمكتمل',
  'mark_as_incomplete': 'تحديد كغير مكتمل',
};
