const Map<String, String> enUS = {
  'app_name': 'KanbanKit',
  'todo': 'To Do',
  'in_progress': 'In Progress',
  'done': 'Done',
  'add_task': 'Add Task',
  'task_title': 'Task Title',
  'task_description': 'Task Description',
  'cancel': 'Cancel',
  'add': 'Add',
  'no_tasks': 'No Tasks',
  'no_task_available': 'No Task Available',
  'edit_task': 'Edit Task',
  'new_task': 'New Task',
  'please_enter_title': 'Please enter title',
  'please_enter_description': 'Please enter description',
  'task_status': 'Task Status',
  'priority': 'Priority',
  'due_date': 'Due Date',
  'select_due_date': 'Select Due Date',
  'high': 'High',
  'medium': 'Medium',
  'low': 'Low',
  'clear_due_date': 'Clear Due Date',
  'update': 'Update',
  'create': 'Create',
  'delete': 'Delete',
  'delete_task': 'Delete Task',
  'are_you_sure_delete': 'Are you sure you want to delete',
  'language': 'Language',
  'refresh': 'Refresh',
  'change_language': 'Change Language',
  'choose_language': 'Choose Language',
  'select_language': 'Select Language',
  'theme': 'Theme',
  'choose_theme': 'Choose Theme',
  'light_theme': 'Light',
  'dark_theme': 'Dark',
  'system_theme': 'System',
  'always_use_light_theme': 'Always use light theme',
  'always_use_dark_theme': 'Always use dark theme',
  'follow_system_theme': 'Follow system theme',
  'switch_theme': 'Switch Theme',
  'details_tab':'Details',
  'checklist_tab':'Checklist',
  'add_checklist_item':'Add checklist item',
  'no_checklist_items':'No checklist items',
  'add_items_above_to_create_checklist':'Add items above to create checklist',
  'adding_item':'Adding item',
  'updating':'Updating',
  'choose_when_this_task_should_be_completed':'Choose when this task should be completed',
   'task_checklist': 'Task Checklist',
  'add_checklist_items_for_new_task': 'Add checklist items for this new task',
  'add_checklist_item_hint': 'Add checklist item...',
  'items_to_add': 'Items to add',
  'no_checklist_items_yet': 'No checklist items yet',
  'add_items_above_to_break_down_task': 'Add items above to break down this task',
  'new_items_to_add': 'New items to add',
  'break_down_task_into_smaller_steps': 'Break down this task into smaller steps',
};
