const Map<String, String> enUS = {
  'app_name': 'KanbanKit',
  'todo': 'To Do',
  'in_progress': 'In Progress',
  'done': 'Done',
  'add_task': 'Add Task',
  'task_title': 'Task Title',
  'task_description': 'Task Description',
  'cancel': 'Cancel',
  'add': 'Add',
  'no_tasks': 'No Tasks',
  'no_task_available': 'No Task Available',
  'edit_task': 'Edit Task',
  'new_task': 'New Task',
  'please_enter_title': 'Please enter title',
  'please_enter_description': 'Please enter description',
  'task_status': 'Task Status',
  'priority': 'Priority',
  'due_date': 'Due Date',
  'select_due_date': 'Select Due Date',
  'high': 'High',
  'medium': 'Medium',
  'low': 'Low',
  'clear_due_date': 'Clear Due Date',
  'update': 'Update',
  'create': 'Create',
  'delete': 'Delete',
  'delete_task': 'Delete Task',
  'are_you_sure_delete': 'Are you sure you want to delete',
  'language': 'Language',
  'refresh': 'Refresh',
  'change_language': 'Change Language',
  'choose_language': 'Choose Language',
  'select_language': 'Select Language',
  'theme': 'Theme',
  'choose_theme': 'Choose Theme',
  'light_theme': 'Light',
  'dark_theme': 'Dark',
  'system_theme': 'System',
  'always_use_light_theme': 'Always use light theme',
  'always_use_dark_theme': 'Always use dark theme',
  'follow_system_theme': 'Follow system theme',
  'switch_theme': 'Switch Theme',

  // Onboarding
  'previous': 'Previous',
  'next': 'Next',
  'skip': 'Skip',
  'get_started': 'Get Started',
  'welcome_to_kanban_kit': 'Welcome to KanbanKit',
  'organize_tasks_effectively': 'Organize Tasks Effectively',
  'kanban_kit_helps_you_manage_tasks':
      'KanbanKit helps you manage your tasks and projects with a simple, visual Kanban board approach.',
  'create_and_manage_tasks': 'Create & Manage Tasks',
  'stay_organized': 'Stay Organized',
  'create_tasks_with_details':
      'Create tasks with descriptions, due dates, priorities, and track their progress effortlessly.',
  'track_progress': 'Track Progress',
  'visualize_workflow': 'Visualize Your Workflow',
  'move_tasks_between_columns':
      'Move tasks between To Do, In Progress, and Done columns to visualize your workflow clearly.',
  'checklist_feature': 'Checklist Feature',
  'break_down_complex_tasks': 'Break Down Complex Tasks',
  'add_checklist_items_to_tasks':
      'Add checklist items to your tasks to break down complex work into manageable steps.',
  'ready_to_begin_journey': 'Ready to Begin Your Journey?',
  'start_using_kanban_kit_today':
      'Start using KanbanKit today to boost your productivity and keep your projects organized!',
  'details_tab': 'Details',
  'checklist_tab': 'Checklist',
  'add_checklist_item': 'Add checklist item',
  'no_checklist_items': 'No checklist items',
  'add_items_above_to_create_checklist': 'Add items above to create checklist',
  'adding_item': 'Adding item',
  'updating': 'Updating',
  'choose_when_this_task_should_be_completed':
      'Choose when this task should be completed',
  'task_checklist': 'Task Checklist',
  'add_checklist_items_for_new_task': 'Add checklist items for this new task',
  'add_checklist_item_hint': 'Add checklist item...',
  'items_to_add': 'Items to add',
  'no_checklist_items_yet': 'No checklist items yet',
  'add_items_above_to_break_down_task':
      'Add items above to break down this task',
  'new_items_to_add': 'New items to add',
  'break_down_task_into_smaller_steps':
      'Break down this task into smaller steps',
  'view_all': 'View All',
  'items': 'Items',
  'checklist': 'Checklist',
  'created': 'Created',
  'of': 'of',
  'completed': 'completed',
  'all_items_completed': 'All items completed',
  'clear': 'Clear',
  'clear_completed_items': 'Clear completed items',
  'are_you_sure': 'Are you sure',
  'mark_all_items': 'mark all',
  'uncomplete_all_items': 'Mark all incomplete',
  'complete_all_items': 'Mark all complete',
  'search_checklist_items': 'Search checklist items...',
  'edit_item': 'Edit item',
  'delete_item': 'Delete item',
  'save_changes': 'Save changes',
  'discard_changes': 'Discard changes',
  'item_title_empty': 'Item title cannot be empty',
  'tap_to_edit': 'Tap to edit',
  'long_press_to_edit': 'Long press to edit',
  'mark_as_complete': 'Mark as complete',
  'mark_as_incomplete': 'Mark as incomplete',
  'task_not_found': 'Task not found',
  'task_details': 'Task details',
  'add_item': 'Add item',
  'add_items': 'Add items',
  'add_multiple_items_hint': 'Add multiple items',
  'task_information': 'Task Information',
  'task_progress': 'Task Progress',
  'all_tasks_completed': 'All tasks completed',
  'last_updated': 'Last Updated',
  'task_priority': 'Task Priority',
  'task_due_date': 'Task Due Date',
  'no_due_date': 'No Due Date',
  'no_description': 'No Description',
  "error": "Error",
  "success": "Success",
  "task_added_successfully": "Task added successfully",
  "task_updated_successfully": "Task updated successfully",
  "task_deleted_successfully": "Task deleted successfully",
  "automatic_move": "Automatic Move",
  "task_moved_to": "Task moved to {status}",
  "failed_to_load_tasks": "Failed to load tasks",
  "failed_to_add_task": "Failed to add task",
  "failed_to_update_task": "Failed to update task",
  "failed_to_delete_task": "Failed to delete task",
  "tasks_moved_automatically": "{count} task(s) moved automatically",
  "task_moved_to_status_automatically": "Task moved to {status} automatically",
  'deleting': 'Deleting',
  'task_moved_to_status': 'Task moved to {status}',

  'single_line': 'Single line',
  'multiple_lines': 'Multiple lines',
  'add_multiple_items': 'Add multiple items',
  "error_loading_checklist": "Error loading checklist",
  "invalid_input": "Invalid input",
  "checklist_item_title_empty": "Checklist item title cannot be empty",

  "checklist_item_created_successfully": "Checklist item created successfully",
  "checklist_items_created_successfully": "Created {count} checklist items",
  "error_creating_item": "Error creating checklist item",
  "error_creating_items": "Error creating checklist items",
  "checklist_item_updated_successfully": "Checklist item updated successfully",
  "error_updating_item": "Error updating checklist item",
  "error_toggling_item": "Error toggling checklist item",
  "error_deleting_item": "Error deleting checklist item",
  "checklist_item_deleted_successfully": "Checklist item deleted successfully",
  "error_deleting_items": "Error deleting checklist items",
  "checklist_items_deleted_successfully": "Deleted {count} checklist items",
  "error_reordering_items": "Error reordering checklist items",
  "error_moving_item": "Error moving checklist item",
  "cleared_completed_items": "Cleared all completed items",
  "error_clearing_items": "Error clearing completed items",
  "marked_all_items": "Marked all items as {action}",
  "error_updating_all_items": "Error updating all items",
  "error_searching_items": "Error searching checklist items",
  "duplicated_checklist_items": "Duplicated {count} checklist items",
  "error_duplicating_items": "Error duplicating checklist items",
  "task_moved_automatically": "Task moved to {status} automatically",
  "loading": "Loading...",
  "organize_your_tasks_efficiently": "Organize your tasks efficiently",

  // Board-related translations
  "create_new_board": "Create New Board",
  "edit_board": "Edit Board",
  "set_up_new_board": "Set up your new board",
  "update_board_settings": "Update your board settings",
  "board_name": "Board Name",
  "enter_board_name": "Enter board name",
  "board_description": "Description",
  "describe_board_purpose": "Describe what this board is for...",
  "board_color": "Board Color",
  "description_optional": "Description (Optional)",
  "please_enter_board_name": "Please enter a board name",
  "board_name_too_long": "Board name cannot exceed 255 characters",
  "hex_color": "Hex Color",
  "quick_colors": "Quick Colors",

  // Board actions
  "edit": "Edit",
  "duplicate": "Duplicate",
  "archive": "Archive",
  "archived": "Archived",
  "just_now": "Just now",
  "days_ago": "{count}d ago",
  "hours_ago": "{count}h ago",
  "minutes_ago": "{count}m ago",

  // Additional UI translations
  "search_boards": "Search Boards",
  "archived_boards": "Archived Boards",
  "your_boards": "Your Boards",
  "search_results": "Search Results",
  "no_boards_yet": "No boards yet",
  "create_first_board":
      "Create your first board to get started with organizing your tasks",
  "add_board": "Add Board",
  "searching_for": "Searching for",
  "archive_board": "Archive Board",
  "delete_board": "Delete Board",
  "duplicate_board": "Duplicate Board",
  "new_board_name": "New board name",
  "are_you_sure_archive": "Are you sure you want to archive",
  "cannot_be_undone": "This action cannot be undone",

  // Archived boards translations
  "no_archived_boards": "No archived boards",
  "archived_boards_will_appear_here":
      "Archived boards will appear here when you archive them",
  "go_back": "Go Back",
  "restore_board": "Restore Board",
  "are_you_sure_restore": "Are you sure you want to restore",
  "restore": "Restore",
  "permanently_delete_board": "Permanently Delete Board",
  "permanently_delete_warning": "Are you sure you want to permanently delete",
  "permanently_delete": "Permanently Delete",
  "view_archived_boards": "View Archived Boards",
  "board_archived_successfully": "Board archived successfully",
  "board_restored_successfully": "Board restored successfully",
};
